[package]
name = "poker-durak"
version = "0.1.0"
authors = ["timcryt"]
edition = "2018"

[dependencies]
rand = "0.3.0"
rouille = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"