[package]
name = "poker-durak"
version = "0.1.0"
authors = ["timcryt"]
edition = "2018"

[dependencies]
rand = "0.7"
rouille = { git = "https://github.com/timcryt/rouille"} 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
fern = "0.5"
chrono = "0.4"
